---
version: '3.8'
services:

  # html:
  #   image: nginx:latest
  #   expose:
  #     - 80
  #     - 443
  #   dns: 172.18.10.1
  #   networks:
  #     edusign-front:
  #       ipv4_address: 172.18.10.200
  #   volumes:
  #     - ./html/etc/html.conf:/etc/nginx/sites-enabled/html.conf:ro
  #     - ./html/www/index.html:/usr/share/nginx/html/index.html:ro
  #     - ./html/www/static:/usr/share/nginx/html/static:ro
  #     - ../frontend/build:/usr/share/nginx/html/front-build:ro
  #   environment:
  #     - "HOSTNAME=html.edusign.docker"

  httpd-proxy:
    build: ./httpd-proxy/
    networks:
      edusign-dev:
        ipv4_address: 172.20.10.200
      edusign-back:
        ipv4_address: 172.19.10.200
    ports:
     - "80:80"
     - "443:443"

  idp:
    build: ./idp/
    depends_on: 
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose: 
     - "4443"
    networks:
      edusign-back:
        ipv4_address: 172.19.10.201
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer     
   
  ldap:
    build: ./ldap/
    networks:
      edusign-back:
        ipv4_address: 172.19.10.202

  sp:
    build: ./edusign/
    expose:
      - 80
      - 443
    dns: 172.20.10.1
    networks:
      edusign-dev:
        ipv4_address: 172.20.10.203
    volumes:
      - ./edusign/config:/opt/config:rw
    environment:
      - "HOSTNAME=sp.edusign.docker"
    depends_on:
      - idp

  www:
    build: ../backend/.
    networks:
      edusign-dev:
        ipv4_address: 172.20.10.204
    expose:
      - 8080
    volumes:
      - ../backend:/opt/edusign/edusign-webapp:ro
    environment:
      - "PYTHONPATH=/opt/edusign/edusign-webapp/src"
      - "HOSTNAME=www.edusign.docker"
    depends_on:
      - sp

networks:
  edusign-back:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign-back
    ipam:
      driver: default
      config:
      - subnet: 172.19.10.0/24
  edusign-dev:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
