---
version: '3.8'
services:

  html:
    image: nginx:latest
    expose:
      - 80
      - 443
    dns: 172.18.10.1
    networks:
      edusign-dev:
        ipv4_address: 172.18.10.200
    volumes:
      - ./html/etc/html.conf:/etc/nginx/sites-enabled/html.conf:ro
      - ./html/www/index.html:/usr/share/nginx/html/index.html:ro
      - ./html/www/static:/usr/share/nginx/html/static:ro
      - ../frontend/build:/usr/share/nginx/html/front-build:ro
    environment:
      - "HOSTNAME=html.edusign.docker"

  idp:
    image: unicon/shibboleth-idp:latest
    expose:
      - 80
      - 443
    dns: 172.18.10.1
    networks:
      edusign-dev:
        ipv4_address: 172.18.10.201
    volumes:
      - ./shibboleth-idp:/opt/shibboleth-idp:rw
    environment:
      - "HOSTNAME=idp.edusign.docker"
      - "JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=secret"
      - "JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=secret"

  sp:
    build: ./edusign/.
    expose:
      - 80
      - 443
    dns: 172.18.10.1
    networks:
      edusign-dev:
        ipv4_address: 172.18.10.202
    volumes:
      - ./edusign/config:/opt/config:rw
    environment:
      - "HOSTNAME=sp.edusign.docker"
    depends_on:
      - idp

  www:
    build: ../backend/.
    networks:
      edusign-dev:
        ipv4_address: 172.18.10.203
    expose:
      - 8080
    volumes:
      - ../backend:/opt/edusign/edusign-webapp:ro
    environment:
      - "PYTHONPATH=/opt/backend/src"
      - "HOSTNAME=www.edusign.docker"
    depends_on:
      - sp

networks:
  edusign-dev:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.18.10.0/24
