---
version: '3.8'
services:

  build-front:
    build: ../frontend/.
    environment:
      - NODE_ENV=production
    volumes:
      - jsbuild:/opt/fronted/build

  sp:
    build: ./edusign/
    expose:
      - 80
      - 443
    networks:
      edusign:
        ipv4_address: 172.20.10.203
    volumes:
      - jsbuild:/opt/edusign/jsbuild:ro
      - edusignlogs:/var/log/edusign:rw
    environment:
      - "HOSTNAME=${SERVER_NAME}"
    depends_on:
      - build-front

  www:
    build: ../backend/.
    networks:
      edusign:
        ipv4_address: 172.20.10.204
    expose:
      - 8080
    volumes:
      - ../backend:/opt/edusign/edusign-webapp:ro
      - edusignlogs:/var/log/edusign:rw
    environment:
      - "PYTHONPATH=/opt/edusign/edusign-webapp/src"
    env_file: .env
    depends_on:
      - sp

volumes:
  edusignlogs:
    name: edusignlogs
  jsbuild:
    name: jsbuild

networks:
  edusign:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24
