---
version: '3.8'
services:

  sp:
    build: .
    ports:
      - 80:80
    networks:
      edusign-dev:
        ipv4_address: 172.20.10.203
    volumes:
      - edusignlogs:/var/log/edusign:rw
      - ../frontend/build:/opt/edusign/jsbuild:ro
    environment:
      - "HOSTNAME=sp.edusign.docker"
    depends_on:
      - www

  redis:
    image: redis:latest
    networks:
      edusign-dev:
        ipv4_address: 172.20.10.205

  www:
    build: ../backend/.
    networks:
      edusign-dev:
        ipv4_address: 172.20.10.204
    expose:
      - 8080
    volumes:
      - edusignlogs:/var/log/edusign:rw
      - ../backend:/opt/edusign/edusign-webapp:ro
      - ../../docker-edusign-app/example-customization:/etc/edusign:ro
    environment:
      - "PYTHONPATH=/opt/edusign/edusign-webapp/src"
      - "HOSTNAME=sp.edusign.docker"
      - "SP_HOSTNAME=sp.edusign.docker"
      - "DEBUG=True"
      - "ENVIRONMENT=development"
      - "SESSION_COOKIE_SECURE=False"
      - "PREFERRED_URL_SCHEME=http"
      - "EDUSIGN_API_PROFILE=edusign-test"
      - "MAIL_SUPPRESS_SEND=True"
      - "MAIL_BACKEND=dummy"
      - "APP_IN_TWO_PATHS=True"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  edusignlogs:
    name: edusignlogs

networks:
  edusign-dev:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24
