---
version: '3.8'
services:

  sp:
    build: ./edusign/
    expose:
      - 80
      - 443
    dns: 172.20.10.1
    networks:
      edusign:
        ipv4_address: 172.20.10.203
    volumes:
      - ./logs/nginx:/var/log/nginx:rw
      - ./logs/shibboleth:/var/log/supervisor:rw
      - ./logs/shibd:/var/log/shibboleth:rw
      - ../frontend:/opt/edusign/frontend:ro
    environment:
      - "HOSTNAME=${SP_HOSTNAME}"

  www:
    build: ../backend/.
    networks:
      edusign:
        ipv4_address: 172.20.10.204
    expose:
      - 8080
    volumes:
      - ../backend:/opt/edusign/edusign-webapp:ro
      - ./logs/edusign:/var/log/edusign:rw
    environment:
      - "PYTHONPATH=/opt/edusign/edusign-webapp/src"
      - "HOSTNAME=${WEBAPP_HOSTNAME}"
    env_file: .env
    depends_on:
      - sp

networks:
  edusign:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-edusign
    ipam:
      driver: default
      config:
      - subnet: 172.20.10.0/24
